
[window]
padding = { x = 0, y = 0 }
decorations = "None"
opacity = 0.90
blur = true
title = "Alacritty Terminal"
dynamic_title = true
dynamic_padding = true

[font]
# normal = { family = "Hasklug Nerd Font", style = "Regular" }
# normal = { family = "TerminessNerdFontMono", style = "Regular" }
normal = { family = "UbuntuMono", style = "Regular" }
size = 12
offset = {x = 0, y = 0}

[general]
live_config_reload = true
#Alacritty Config for Yankee

import = [
#"~/.config/alacritty/nightfox.toml",
"~/.config/alacritty/everforest_dark.toml"
]

[mouse]
hide_when_typing = true
